### ISSUE TITLE
ENOENT: no such file or directory, open 'sessions/.json'

### ISSUE THREAD

**Issue by oschn0r** [valery-barysok/session-file-store#26]
Yesterday evening, all was working fine. Today it throws following message

```[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/.json' ```

```
...
var cookieParser 		= require('cookie-parser');
var session 			= require('express-session');
var FileStore 			= require('session-file-store')(session);
var sessionstore 		= new FileStore();

app.use(cookieParser());
app.use(session({
					name: 'server-session-cookie-id', 
					secret: config.cookie.secret,
					saveUninitialized: true, 
					resave: true,
					store: sessionstore,
					cookie: { maxAge : config.cookie.maxage }
				}));
app.use(passport.initialize());
app.use(passport.session());
...
```

Dont know what goes wrong.

**Comment by johnstonmatt** [comment]
I'm having a similar problem `[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/foo.json'` this error is causing crashes.

**Comment by kidandcat** [comment]
Same error

**Comment by kynetiv** [comment]
Was getting this error as well after upgrading. I was on v0.0.18 and just reverted back -- session files are being created again and I'm not noticing the error.

**Comment by harrymoore** [comment]
same error. using 0.0.21. error repeats many times
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/Y84fiubaTxz5J08ZiUVWIXDC7PpeSXmt.json'

**Comment by carloscarcamo** [comment]
I'm getting something similar when destroying the session, the logout code is:

```js
router.get('/logout', function(req, res, next) {
  req.session.destroy(function(err) {
    if (err) {
      console.error(err);
    } else {
      res.redirect('/');
    }
  });
});
```
When redirecting to the index, the console shows something like:

```
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/9727KdeaK9Tpt4OxWTh4LljUg8uhISXh.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/9727KdeaK9Tpt4OxWTh4LljUg8uhISXh.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/9727KdeaK9Tpt4OxWTh4LljUg8uhISXh.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/9727KdeaK9Tpt4OxWTh4LljUg8uhISXh.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/9727KdeaK9Tpt4OxWTh4LljUg8uhISXh.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/9727KdeaK9Tpt4OxWTh4LljUg8uhISXh.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/9727KdeaK9Tpt4OxWTh4LljUg8uhISXh.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/9727KdeaK9Tpt4OxWTh4LljUg8uhISXh.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/9727KdeaK9Tpt4OxWTh4LljUg8uhISXh.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/9727KdeaK9Tpt4OxWTh4LljUg8uhISXh.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/9727KdeaK9Tpt4OxWTh4LljUg8uhISXh.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/9727KdeaK9Tpt4OxWTh4LljUg8uhISXh.json'
...
```

After that, the index is displayed, is this normal?

This is the config code:

```js
...
var session = require('express-session');
var FileStore = require('session-file-store')(session);

app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

// session config
var sess_options =
  { retries   : 50
  , minTimeout: 100
  , maxTimeout: 200
  };

app.use(session(
  { secret: 'my_secret'
  , store: new FileStore(sess_options)
  , resave: true
  , saveUninitialized: true
  }
));
...
```

**Comment by valery-barysok** [comment]
I believe this issue resolved by #31

**Comment by carloscarcamo** [comment]
@valery-barysok I've updated to the latest version, but i'm still having this issue, I wonder if this is normal.

```
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/pQPZjW2gS3DePsQFyyslr2hi-mpGLsV0.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/pQPZjW2gS3DePsQFyyslr2hi-mpGLsV0.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/pQPZjW2gS3DePsQFyyslr2hi-mpGLsV0.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/pQPZjW2gS3DePsQFyyslr2hi-mpGLsV0.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/pQPZjW2gS3DePsQFyyslr2hi-mpGLsV0.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/pQPZjW2gS3DePsQFyyslr2hi-mpGLsV0.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/pQPZjW2gS3DePsQFyyslr2hi-mpGLsV0.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/pQPZjW2gS3DePsQFyyslr2hi-mpGLsV0.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/pQPZjW2gS3DePsQFyyslr2hi-mpGLsV0.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/pQPZjW2gS3DePsQFyyslr2hi-mpGLsV0.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/pQPZjW2gS3DePsQFyyslr2hi-mpGLsV0.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/pQPZjW2gS3DePsQFyyslr2hi-mpGLsV0.json'
....
```

I got this after destroying a session and redirecting to another route. Is that normal?

**Comment by valery-barysok** [comment]
@carloscarcamo, i think you got it because you destroyed session but you kept cookie with session id and it tried to read session file after redirect.

**Comment by valery-barysok** [comment]
@carloscarcamo, i just tested your use case.

```js
var express = require('express');
var app = express();
var session = require('express-session');
var FileStore = require('session-file-store')(session);

var options = {
  store: new FileStore,
  secret: 'keyboard cat',
  resave: true,
  saveUninitialized: true,
  name: 'my.connect.sid'
};

app.use(session(options));

app.get('/', function (req, res) {
  if (req.session.views) {
    req.session.views++;
    res.setHeader('Content-Type', 'text/html');
    res.write('<p>views: ' + req.session.views + '</p>');
    res.end();
  } else {
    req.session.views = 1;
    res.end('Welcome to the file session demo. Refresh page!');
  }
});

app.get('/destroy', function (req, res) {
  req.session.destroy(function(err) {
    if (err) {
      console.error(err);
    } else {
      **res.clearCookie(options.name);**
      res.redirect('/');
    }
  });
});

var server = app.listen(1337, function () {
  var host = server.address().address;
  var port = server.address().port;

  console.log('Example app listening at http://%s:%s', host, port);
});
```

**Comment by valery-barysok** [comment]
@carloscarcamo, your use case does not related to session store because session store does not work with request and response. But `express-session` does. So i believe you can create issue there.

**Comment by carloscarcamo** [comment]
@valery-barysok  I used `res.clearCookie(options.name);` as you suggest and now my app works like a charm, I really appreciate your help, thanks.

**Comment by Nilegfx** [comment]
I had the same problem and I was able to fix it by `chmod +x sessions`

**Comment by idchlife** [comment]
@Nilegfx this is the solution

**Comment by MikleSmart** [comment]
@Nilegfx To which directory did you apply this commend?
